---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.4

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[git-daemon::default]
    attributes:
