---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-8.5
    run_list:
      - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[git-daemon::default]
    attributes:
