driver:
  name: docker
  use_sudo: false
  run_command: /bin/systemd # required!
  cap_add:
    - SYS_ADMIN
  volume:
    - /sys/fs/cgroup # required!
  provision_command:
    - apt-get install -y systemd
    - apt-get install -y net-tools cron
